#ifndef CPP_TOOLS_SCAFFOLD_TPL_SOURCE_HPP
#define CPP_TOOLS_SCAFFOLD_TPL_SOURCE_HPP

#include <string>

namespace Scaffold {

std::string tpl_source = R"~(// Generated by Scaffold.
namespace {{NAMESPACE}} {

{{CODE}}

} // {{NAMESPACE}}
)~";

} // Scaffold

#endif // CPP_TOOLS_SCAFFOLD_TPL_SOURCE_HPP
